version: "3"
name: woodytoys
services:
  resolver:
    image: resolver
    links:
      - client1
      - client2
    networks:
      resolver-nw:
        ipv4_address: "10.0.10.3"
    ports:
      - 53:53/udp
      - 53:53
    
  mail:
    image: mail
    links:
      - client1
      - client2
    networks:
      resolver-nw:
        ipv4_address: "10.0.10.4"
    ports:
      - 25:25
  client1:
    image: client
    entrypoint: /bin/bash -i
    stdin_open: true
    tty: true
    networks:
      resolver-nw:
        ipv4_address: "10.0.10.253"
  client2:
    image: client
    entrypoint: /bin/bash -i
    stdin_open: true
    tty: true
    networks:
      resolver-nw:
        ipv4_address: "10.0.10.252"
    

networks:
  resolver-nw:
    ipam:
     config:
       - subnet: 10.0.10.0/24
