FROM ubuntu:latest

# MAINTAINER instruction is deprecated
LABEL maintainers="Austreelis <dev@austreelis.net>"

RUN apt update
RUN apt install -y --no-install-recommends \
  bind9-dnsutils \
  iputils-ping \
  iproute2

