version: "3.2"

services:
# ---
  test-bind9:
    image: ubuntu/bind9:9.18-22.04_beta
    container_name: test-bind9
    environment:
      - TZ=Europe/Brussels
      - BIND9_USER=root
    volumes:
      - /var/lib/woodytoys/services/test-bind9/config:/etc/bind:ro
      - /var/lib/woodytoys/services/test-bind9/records:/var/lib/bind:ro
      - type: tmpfs
        target: /var/cache/bind
    #networks:
    #  ipvlan-l3:
    #    ipv4_address: 10.0.0.2
    #restart: unless-stopped
# ---
  test-client:
    container_name: test-client
    image: client
    restart: unless-stopped
    #dns:
    #  - 10.0.0.2
    #networks:
    #  ipvlan-l3:
    #    ipv4_address: 10.0.1.2