version: "3.2"
services:
# ---
  hangar:
    container_name: hangar
    image: client
    stdin_open: true
    tty: true
    restart: unless-stopped
    dns:
      - 10.0.0.2
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.1.2
# ---
  production:
    container_name: production
    image: client
    stdin_open: true
    tty: true
    restart: unless-stopped
    dns:
      - 10.0.0.2
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.2.2
# ---
  accounting:
    container_name: accounting
    image: client
    stdin_open: true
    tty: true
    restart: unless-stopped
    dns:
      - 10.0.0.2
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.3.2
# ---
  marketing:
    container_name: marketing
    image: client
    stdin_open: true
    tty: true
    restart: unless-stopped
    dns:
      - 10.0.0.2
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.4.2
# ---
  secretariat:
    container_name: secretariat
    image: client
    stdin_open: true
    tty: true
    restart: unless-stopped
    dns:
      - 10.0.0.2
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.5.2
# ---
  management:
    container_name: management
    image: client
    stdin_open: true
    tty: true
    restart: unless-stopped
    dns:
      - 10.0.0.2
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.6.2
# ---
networks:
  woodytoys-intra-l3ipvlan:
    # external: true
    name: woodytoys-intra-l3ipvlan
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l3
      parent: ens4
    ipam:
      config:
        - subnet: 10.0.0.0/24
        - subnet: 10.0.1.0/24
        - subnet: 10.0.2.0/24
        - subnet: 10.0.3.0/24
        - subnet: 10.0.4.0/24
        - subnet: 10.0.5.0/24
        - subnet: 10.0.6.0/24
        - subnet: 10.0.7.0/24
