version: "3.2"
services:
# ---
  bind9:
    container_name: bind9
    image: ubuntu/bind9:9.18-22.04_beta
    restart: unless-stopped
    healthcheck:
      test: >-
        dig @ns.woodytoys.home a in +noall +answer woodytoys.home
          | grep -i 'ns\.woodytoys\.home\..\+in\s\+a' || exit 1
        && dig @localhost any in +noall +answer || exit 1
      interval: 1m
      timeout: 10s
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.0.2
    volumes:
      - /home/user/git/woodytoys/services/bind9/config:/etc/bind
      - bind9-records:/var/lib/bind
      - type: tmpfs
        target: /var/cache/bind
    environment:
      - TZ=Europe/Brussels
      - BIND9_USER=root
# ---
  erp:
    container_name: erp
    image: php-apache
    # depends_on:
    #   - mysql
    healthcheck:
      # TODO: Add api endpoint and chck db connetion that way ?
      test: curl -f --fail-early http://localhost:80 || exit 1
      interval: 1m
      timeout: 10s
    networks:
      mysql:
      erp-intra:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.0.5
    ports:
        - '8001:80'
    restart: unless-stopped
    volumes:
        - /home/user/git/woodytoys/services/erp/html:/var/www/html/:ro
# ---
  # mysql:
  #   container_name: mysql
  #   image: mysql
  #   ports:
  #       - "9906:3306"
  #   healthcheck:
  #     test: mysqladmin ping -h localhost || exit 1
  #     interval: 1m
  #     timeout: 10s
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
  #     MYSQL_DATABASE: MYSQL_DATABASE
  #     MYSQL_USER: MYSQL_USER
  #     MYSQL_PASSWORD: MYSQL_PASSWORD
  #   # networks:
  #   #   woodytoys-intra-l3ipvlan:
  #   #     ipv4_address: 10.0.0.6
  #   restart: unless-stopped
# ---
  wiki:
    image: mdbook
    healthcheck:
      test: curl -f --fail-early http://localhost:80 || exit 1
      interval: 1m
      timeout: 10s
    restart: unless-stopped
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.0.7

# ---
volumes:
  mysql:
  bind9-records:
# ---
networks:
  erp-intra:
    name: erp-intra

  mysql:
    name: mysql
    external: true

  woodytoys-intra-l3ipvlan:
    name: woodytoys-intra-l3ipvlan
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l3
      parent: ens4
    ipam:
      config:
        - subnet: 10.0.0.0/24
        - subnet: 10.0.1.0/24
        - subnet: 10.0.2.0/24
        - subnet: 10.0.3.0/24
        - subnet: 10.0.4.0/24
        - subnet: 10.0.5.0/24
        - subnet: 10.0.6.0/24
        - subnet: 10.0.7.0/24

