version: "3.2"

networks:
  woodytoys-intra-l3ipvlan:
    external: true
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l3
      parent: wlan0
    ipam:
      config:
        - subnet: 10.0.1.0/24
        - subnet: 10.0.2.0/24
        - subnet: 10.0.3.0/24
        - subnet: 10.0.4.0/24
        - subnet: 10.0.5.0/24
        - subnet: 10.0.6.0/24
        - subnet: 10.0.7.0/24
        - subnet: 10.0.8.0/24

volumes:
  mysql:
  bind9-records:

services:
  b2b:
    image: php:8-apache
    ports:
      - 8000:80
    depends_on:
      - mysql
    restart: unless-stopped
    healthcheck:
      # TODO: Add api endpoint and chck db connetion that way ?
      test: curl -f --fail-early http://localhost:80 || exit 1
      interval: 1m
      timeout: 10s
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.1.4
    volumes:
      - /var/lib/woodytoys/services/b2b/html:/var/www/html/:ro

  bind9:
    image: ubuntu/bind9:9.18-22.04_beta
    restart: unless-stopped
    healthcheck:
      test: >-
        dig @ns.woodytoys.home a in +noall +answer woodytoys.home
          | grep -i 'ns\.woodytoys\.home\..\+in\s\+a' || exit 1
        && dig @localhost any in +noall +answer || exit 1
      interval: 1m
      timeout: 10s
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.1.2
    volumes:
      - /var/lib/woodytoys/services/bind9/config:/etc/bind:ro
      - bind9-records:/var/lib/bind
      - type: tmpfs
        target: /var/cache/bind
    environment:
      - TZ=Europe/Brussels
      - BIND9_USER=root

  erp:
    image: php:8-apache
    depends_on:
      - mysql
    healthcheck:
      # TODO: Add api endpoint and chck db connetion that way ?
      test: curl -f --fail-early http://localhost:80 || exit 1
      interval: 1m
      timeout: 10s
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.1.5
    ports:
        - 8001:80
    restart: unless-stopped
    volumes:
        - /var/lib/woodytoys/services/erp/html:/var/www/html/:ro

  mysql:
    image: mysql
    ports:
        - "9906:3306"
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h localhost || exit 1
      interval: 1m
      timeout: 10s
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.1.6
    volumes:
      - mysql:/var/lib/mysql
    environment:
        MYSQL_DATABASE: MYSQL_DATABASE
        MYSQL_PASSWORD: MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_USER: MYSQL_USER

  www:
    image: httpd:latest
    healthcheck:
      test: curl -f --fail-early http://localhost:80 || exit 1
      interval: 1m
      timeout: 10s
    restart: unless-stopped
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.1.3
    volumes:
      - /var/lib/woodytoys/services/www/htdocs:/usr/local/apache2/htdocs:ro

  wiki:
    build: /var/lib/woodytoys/images/mdbook
    image: woodytoys/mdbook
    healthcheck:
      test: curl -f --fail-early http://localhost:80 || exit 1
      interval: 1m
      timeout: 10s
    restart: unless-stopped
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.1.7

  postfix:
    build: /var/lib/woodytoys/images/mail/postfix
    image: woodytoys/mail
    ports:
        - 25:25
        - 587:587
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.1.8
    restart: unless-stopped
    volumes:
      - /var/lib/woodytoys/services/mail/postfix/main.cf:/etc/postfix/main.cf

  dovecot:
    build: /var/lib/woodytoys/images/mail/dovecot
    image: woodytoys/dovecot
    ports:
        - 143:143
        - 993:993
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.1.9
    restart: unless-stopped
    volumes:
      - /var/lib/woodytoys/services/mail/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
