version: "3.2"

networks:
  woodytoys-intra-l3ipvlan:
    external: true
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l3
      parent: wlan0
    ipam:
      config:
        - subnet: 10.0.1.0/24
        - subnet: 10.0.2.0/24
        - subnet: 10.0.3.0/24
        - subnet: 10.0.4.0/24
        - subnet: 10.0.5.0/24
        - subnet: 10.0.6.0/24
        - subnet: 10.0.7.0/24
        - subnet: 10.0.8.0/24

volumes:
  mysql:
  bind9-records:

services:
  b2b:
    image: php:8-apache
    ports:
      - 8000:80
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.1.4
    volumes:
      - /var/lib/woodytoys/services/b2b/html:/var/www/html/:ro

  bind9:
    image: ubuntu/bind9:9.18-22.04_beta
    restart: unless-stopped
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.1.2
    volumes:
      - /var/lib/woodytoys/services/bind9/config:/etc/bind:ro
      - bind9-records:/var/lib/bind
      - type: tmpfs
        target: /var/cache/bind
    environment:
      - TZ=Europe/Brussels
      - BIND9_USER=root

  erp:
    image: php:8-apache
    depends_on:
      - mysql
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.1.5
    ports:
        - 8001:80
    restart: unless-stopped
    volumes:
        - /var/lib/woodytoys/services/erp/html:/var/www/html/:ro

  mysql:
    image: mysql
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.1.6
    ports:
        - "9906:3306"
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    environment:
        MYSQL_DATABASE: MYSQL_DATABASE
        MYSQL_PASSWORD: MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_USER: MYSQL_USER

  www:
    image: httpd:latest
    networks:
      woodytoys-intra-l3ipvlan:
        ipv4_address: 10.0.1.3
    restart: unless-stopped
    volumes:
      - /var/lib/woodytoys/services/www/htdocs:/usr/local/apache2/htdocs:ro

